use crate::database::Database;
use serde::Serialize;
use std::{
    collections::{HashMap, HashSet},
    env, fs, io,
    path::{Path, PathBuf},
    sync::{Mutex, MutexGuard, OnceLock},
    time::{SystemTime, UNIX_EPOCH},
};
use tauri_plugin_opener::OpenerExt;

const MANAGED_HEADER: &str = "<!-- Generated by Agent Manager. Do not edit manually. -->";
static WRITE_LOCK: OnceLock<Mutex<()>> = OnceLock::new();

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentsMdFragment {
    pub id: i64,
    pub title: String,
    pub content: String,
    pub enabled: bool,
    pub sort_order: i64,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentsMdDashboard {
    pub fragments: Vec<AgentsMdFragment>,
    pub target_path: String,
    pub combined_content: String,
    pub enabled_content_chars: usize,
}

struct Store {
    database: Database,
    agents_dir: PathBuf,
    target_path: PathBuf,
    backup_path: PathBuf,
}

#[derive(Clone)]
struct FileSnapshot {
    target: Option<Vec<u8>>,
    backup: Option<Vec<u8>>,
}

impl Store {
    fn new() -> Result<Self, String> {
        let home = home_dir()?;
        Self::from_root(home.join(".agent-manager"))
    }

    fn from_root(root: PathBuf) -> Result<Self, String> {
        let home = root.parent().ok_or("Agent Manager 根目录无效")?;
        let agents_dir = home.join(".agents");
        Ok(Self {
            database: Database::new(root.join("agent-manager.db"))?,
            target_path: agents_dir.join("AGENTS.md"),
            backup_path: agents_dir.join("AGENTS.md.agent-manager-backup"),
            agents_dir,
        })
    }

    fn dashboard(&self) -> Result<AgentsMdDashboard, String> {
        let fragments = self.database.load_agents_md_fragments()?;
        Ok(AgentsMdDashboard {
            combined_content: render_enabled_agents_md(&fragments),
            enabled_content_chars: enabled_content_char_count(&fragments),
            fragments,
            target_path: self.target_path.to_string_lossy().into_owned(),
        })
    }

    fn mutate(
        &self,
        change: impl FnOnce(&mut Vec<AgentsMdFragment>) -> Result<(), String>,
    ) -> Result<AgentsMdDashboard, String> {
        let old_fragments = self.database.load_agents_md_fragments()?;
        let snapshot = self.snapshot_files()?;
        let mut new_fragments = old_fragments;
        change(&mut new_fragments)?;
        normalize_order(&mut new_fragments);

        if let Err(error) = self.sync_file(&new_fragments) {
            let _ = self.restore_files(&snapshot);
            return Err(error);
        }
        if let Err(error) = self.database.save_agents_md_fragments(&new_fragments) {
            let restore_error = self.restore_files(&snapshot).err();
            return Err(match restore_error {
                Some(restore_error) => {
                    format!("{error}；恢复原 AGENTS.md 文件失败：{restore_error}")
                }
                None => error,
            });
        }
        self.dashboard()
    }

    fn snapshot_files(&self) -> Result<FileSnapshot, String> {
        Ok(FileSnapshot {
            target: read_optional(&self.target_path)?,
            backup: read_optional(&self.backup_path)?,
        })
    }

    fn restore_files(&self, snapshot: &FileSnapshot) -> Result<(), String> {
        fs::create_dir_all(&self.agents_dir)
            .map_err(|error| format!("创建 {} 失败：{error}", self.agents_dir.display()))?;
        restore_optional(&self.target_path, snapshot.target.as_deref())?;
        restore_optional(&self.backup_path, snapshot.backup.as_deref())
    }

    fn sync_file(&self, fragments: &[AgentsMdFragment]) -> Result<(), String> {
        fs::create_dir_all(&self.agents_dir)
            .map_err(|error| format!("创建 {} 失败：{error}", self.agents_dir.display()))?;
        let content = render_enabled_agents_md(fragments);
        if content.is_empty() {
            self.remove_managed_file_and_restore_backup()?;
            return Ok(());
        }

        if let Some(existing) = read_optional(&self.target_path)? {
            let existing_text = String::from_utf8_lossy(&existing);
            if !existing_text.starts_with(MANAGED_HEADER) {
                if self.backup_path.exists() {
                    return Err(format!(
                        "检测到未受管的 {}，且备份文件已存在；请先处理这两个文件",
                        self.target_path.display()
                    ));
                }
                atomic_write(&self.backup_path, &existing)?;
            }
        }

        atomic_write(&self.target_path, content.as_bytes())
    }

    fn remove_managed_file_and_restore_backup(&self) -> Result<(), String> {
        let target = read_optional(&self.target_path)?;
        let target_is_managed = target
            .as_deref()
            .map(|bytes| String::from_utf8_lossy(bytes).starts_with(MANAGED_HEADER))
            .unwrap_or(false);
        if target_is_managed {
            fs::remove_file(&self.target_path)
                .map_err(|error| format!("移除受管 AGENTS.md 失败：{error}"))?;
        }
        if !self.target_path.exists() && self.backup_path.exists() {
            fs::rename(&self.backup_path, &self.target_path)
                .map_err(|error| format!("恢复原 AGENTS.md 失败：{error}"))?;
        }
        Ok(())
    }
}

#[tauri::command]
pub fn get_agents_md_dashboard() -> Result<AgentsMdDashboard, String> {
    Store::new()?.dashboard()
}

#[tauri::command]
pub fn create_agents_md_fragment(
    title: String,
    content: String,
) -> Result<AgentsMdDashboard, String> {
    validate_fragment(&title, &content)?;
    let _guard = try_write_lock()?;
    let now = timestamp();
    Store::new()?.mutate(|fragments| {
        let next_id = fragments.iter().map(|item| item.id).max().unwrap_or(0) + 1;
        fragments.push(AgentsMdFragment {
            id: next_id,
            title: title.trim().to_string(),
            content,
            enabled: false,
            sort_order: fragments.len() as i64,
            created_at: now.clone(),
            updated_at: now,
        });
        Ok(())
    })
}

#[tauri::command]
pub fn update_agents_md_fragment(
    id: i64,
    title: String,
    content: String,
) -> Result<AgentsMdDashboard, String> {
    validate_fragment(&title, &content)?;
    let _guard = try_write_lock()?;
    Store::new()?.mutate(|fragments| {
        let fragment = find_fragment_mut(fragments, id)?;
        fragment.title = title.trim().to_string();
        fragment.content = content;
        fragment.updated_at = timestamp();
        Ok(())
    })
}

#[tauri::command]
pub fn delete_agents_md_fragment(id: i64) -> Result<AgentsMdDashboard, String> {
    let _guard = try_write_lock()?;
    Store::new()?.mutate(|fragments| {
        let index = fragments
            .iter()
            .position(|item| item.id == id)
            .ok_or_else(|| format!("AGENTS.md 片段 {id} 不存在"))?;
        fragments.remove(index);
        Ok(())
    })
}

#[tauri::command]
pub fn set_agents_md_fragment_enabled(id: i64, enabled: bool) -> Result<AgentsMdDashboard, String> {
    let _guard = try_write_lock()?;
    Store::new()?.mutate(|fragments| {
        let fragment = find_fragment_mut(fragments, id)?;
        fragment.enabled = enabled;
        fragment.updated_at = timestamp();
        Ok(())
    })
}

#[tauri::command]
pub fn reorder_agents_md_fragments(ids: Vec<i64>) -> Result<AgentsMdDashboard, String> {
    let _guard = try_write_lock()?;
    Store::new()?.mutate(|fragments| apply_fragment_order(fragments, &ids))
}

#[tauri::command]
pub fn open_agents_md_folder(app: tauri::AppHandle) -> Result<(), String> {
    let store = Store::new()?;
    fs::create_dir_all(&store.agents_dir)
        .map_err(|error| format!("创建 AGENTS.md 文件夹失败：{error}"))?;
    let path = store.agents_dir.to_string_lossy().into_owned();
    app.opener()
        .open_path(&path, None::<&str>)
        .map_err(|error| format!("打开 AGENTS.md 文件夹 {path} 失败：{error}"))
}

fn validate_fragment(title: &str, content: &str) -> Result<(), String> {
    let title = title.trim();
    if title.is_empty() {
        return Err("片段名称不能为空".to_string());
    }
    if title.chars().count() > 120 {
        return Err("片段名称不能超过 120 个字符".to_string());
    }
    if content.trim().is_empty() {
        return Err("Markdown 内容不能为空".to_string());
    }
    Ok(())
}

fn find_fragment_mut(
    fragments: &mut [AgentsMdFragment],
    id: i64,
) -> Result<&mut AgentsMdFragment, String> {
    fragments
        .iter_mut()
        .find(|item| item.id == id)
        .ok_or_else(|| format!("AGENTS.md 片段 {id} 不存在"))
}

fn apply_fragment_order(fragments: &mut [AgentsMdFragment], ids: &[i64]) -> Result<(), String> {
    if ids.len() != fragments.len() {
        return Err("片段排序列表不完整，请刷新后重试".to_string());
    }
    let supplied = ids.iter().copied().collect::<HashSet<_>>();
    if supplied.len() != ids.len() {
        return Err("片段排序列表包含重复项，请刷新后重试".to_string());
    }
    let existing = fragments.iter().map(|item| item.id).collect::<HashSet<_>>();
    if supplied != existing {
        return Err("片段排序列表包含未知片段，请刷新后重试".to_string());
    }
    let positions = ids
        .iter()
        .enumerate()
        .map(|(index, id)| (*id, index as i64))
        .collect::<HashMap<_, _>>();
    for fragment in fragments.iter_mut() {
        fragment.sort_order = positions[&fragment.id];
    }
    fragments.sort_by_key(|item| item.sort_order);
    Ok(())
}

fn normalize_order(fragments: &mut [AgentsMdFragment]) {
    fragments.sort_by_key(|item| (item.sort_order, item.id));
    for (index, fragment) in fragments.iter_mut().enumerate() {
        fragment.sort_order = index as i64;
    }
}

fn render_agents_md(fragments: &[&AgentsMdFragment]) -> String {
    let body = fragments
        .iter()
        .map(|fragment| fragment.content.trim())
        .collect::<Vec<_>>()
        .join("\n\n");
    format!("{MANAGED_HEADER}\n\n{body}\n")
}

fn render_enabled_agents_md(fragments: &[AgentsMdFragment]) -> String {
    let enabled = fragments
        .iter()
        .filter(|fragment| fragment.enabled)
        .collect::<Vec<_>>();
    if enabled.is_empty() {
        String::new()
    } else {
        render_agents_md(&enabled)
    }
}

fn enabled_content_char_count(fragments: &[AgentsMdFragment]) -> usize {
    fragments
        .iter()
        .filter(|fragment| fragment.enabled)
        .map(|fragment| fragment.content.chars().count())
        .sum()
}

fn read_optional(path: &Path) -> Result<Option<Vec<u8>>, String> {
    match fs::read(path) {
        Ok(bytes) => Ok(Some(bytes)),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(None),
        Err(error) => Err(format!("读取 {} 失败：{error}", path.display())),
    }
}

fn restore_optional(path: &Path, content: Option<&[u8]>) -> Result<(), String> {
    match content {
        Some(content) => atomic_write(path, content),
        None => match fs::remove_file(path) {
            Ok(()) => Ok(()),
            Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(()),
            Err(error) => Err(format!("移除 {} 失败：{error}", path.display())),
        },
    }
}

fn atomic_write(path: &Path, content: &[u8]) -> Result<(), String> {
    let parent = path
        .parent()
        .ok_or_else(|| format!("路径 {} 没有父目录", path.display()))?;
    fs::create_dir_all(parent)
        .map_err(|error| format!("创建 {} 失败：{error}", parent.display()))?;
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| format!("文件名 {} 无效", path.display()))?;
    let temporary = parent.join(format!(".{file_name}.{}.tmp", timestamp_nanos()));
    fs::write(&temporary, content)
        .map_err(|error| format!("写入临时文件 {} 失败：{error}", temporary.display()))?;
    if let Err(error) = fs::rename(&temporary, path) {
        let _ = fs::remove_file(&temporary);
        return Err(format!("原子替换 {} 失败：{error}", path.display()));
    }
    Ok(())
}

fn try_write_lock() -> Result<MutexGuard<'static, ()>, String> {
    WRITE_LOCK
        .get_or_init(|| Mutex::new(()))
        .try_lock()
        .map_err(|_| "另一个 AGENTS.md 写入任务正在运行，请稍后再试".to_string())
}

fn home_dir() -> Result<PathBuf, String> {
    env::var_os("HOME")
        .or_else(|| env::var_os("USERPROFILE"))
        .map(PathBuf::from)
        .ok_or_else(|| "无法确定用户主目录".to_string())
}

fn timestamp() -> String {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
        .to_string()
}

fn timestamp_nanos() -> u128 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_store(name: &str) -> (Store, PathBuf) {
        let root = env::temp_dir().join(format!(
            "agent-manager-agents-md-{name}-{}",
            timestamp_nanos()
        ));
        let store = Store::from_root(root.join(".agent-manager")).expect("store");
        (store, root)
    }

    #[test]
    fn composes_enabled_fragments_in_saved_order() {
        let (store, root) = test_store("compose");
        store
            .mutate(|fragments| {
                fragments.push(AgentsMdFragment {
                    id: 1,
                    title: "Second".into(),
                    content: "## Second\n\nB".into(),
                    enabled: true,
                    sort_order: 1,
                    created_at: "1".into(),
                    updated_at: "1".into(),
                });
                fragments.push(AgentsMdFragment {
                    id: 2,
                    title: "First".into(),
                    content: "# First\n\nA".into(),
                    enabled: true,
                    sort_order: 0,
                    created_at: "1".into(),
                    updated_at: "1".into(),
                });
                Ok(())
            })
            .expect("save fragments");
        let content = fs::read_to_string(&store.target_path).expect("generated AGENTS.md");
        assert!(content.starts_with(MANAGED_HEADER));
        assert!(
            content.find("# First").expect("first") < content.find("## Second").expect("second")
        );
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn applies_complete_fragment_order_and_rejects_invalid_ids() {
        let mut fragments = vec![
            test_fragment(1, 0),
            test_fragment(2, 1),
            test_fragment(3, 2),
        ];
        apply_fragment_order(&mut fragments, &[3, 1, 2]).expect("reorder fragments");
        assert_eq!(
            fragments.iter().map(|item| item.id).collect::<Vec<_>>(),
            vec![3, 1, 2]
        );
        assert_eq!(
            fragments
                .iter()
                .map(|item| item.sort_order)
                .collect::<Vec<_>>(),
            vec![0, 1, 2]
        );

        let snapshot = fragments.clone();
        assert!(apply_fragment_order(&mut fragments, &[3, 3, 2]).is_err());
        assert_eq!(
            fragments.iter().map(|item| item.id).collect::<Vec<_>>(),
            snapshot.iter().map(|item| item.id).collect::<Vec<_>>()
        );
        assert!(apply_fragment_order(&mut fragments, &[3, 1, 9]).is_err());
    }

    #[test]
    fn counts_enabled_fragment_content_characters_only() {
        let mut fragments = vec![test_fragment(1, 0), test_fragment(2, 1)];
        fragments[0].content = "# 规范\n中文".into();
        fragments[1].content = "disabled".into();
        fragments[1].enabled = false;
        assert_eq!(
            enabled_content_char_count(&fragments),
            "# 规范\n中文".chars().count()
        );
    }

    fn test_fragment(id: i64, sort_order: i64) -> AgentsMdFragment {
        AgentsMdFragment {
            id,
            title: format!("Fragment {id}"),
            content: format!("# Fragment {id}"),
            enabled: true,
            sort_order,
            created_at: "1".into(),
            updated_at: "1".into(),
        }
    }

    #[test]
    fn preserves_and_restores_existing_agents_md() {
        let (store, root) = test_store("backup");
        fs::create_dir_all(&store.agents_dir).expect("agents dir");
        fs::write(&store.target_path, "# Existing\n").expect("existing file");
        store
            .mutate(|fragments| {
                fragments.push(AgentsMdFragment {
                    id: 1,
                    title: "Managed".into(),
                    content: "# Managed".into(),
                    enabled: true,
                    sort_order: 0,
                    created_at: "1".into(),
                    updated_at: "1".into(),
                });
                Ok(())
            })
            .expect("enable fragment");
        assert_eq!(
            fs::read_to_string(&store.backup_path).expect("backup"),
            "# Existing\n"
        );
        store
            .mutate(|fragments| {
                fragments[0].enabled = false;
                Ok(())
            })
            .expect("disable fragment");
        assert_eq!(
            fs::read_to_string(&store.target_path).expect("restored"),
            "# Existing\n"
        );
        assert!(!store.backup_path.exists());
        let _ = fs::remove_dir_all(root);
    }
}
